# Generated by Django 4.1.7 on 2023-03-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='name',
            field=models.CharField(default='Nova', max_length=255),
            preserve_default=False,
        ),
    ]
