# Generated by Django 4.1.7 on 2023-03-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_doctor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentlink',
            name='hash',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
