# Generated by Django 4.1.7 on 2023-03-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointmentlink_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentlink',
            name='doctor_name',
            field=models.CharField(default='joy', max_length=255),
            preserve_default=False,
        ),
    ]
